
export const LOAD_MEAL_PLANS = 'LOAD_MEAL_PLANS';
export const MEAL_PLAN_SELECTED = 'MEAL_PLAN_SELECTED';
export const LOAD_MEALS = 'LOAD_MEALS';
export const CREATE_MEAL_PLAN = 'CREATE_MEAL_PLAN';
export const DELETE_MEAL_PLAN = 'DELETE_MEAL_PLAN';